export const products = [
  { id: 1, name: "Bananas", price: 1.0, category: "Fruits & Vegetables" },
  { id: 2, name: "Apples", price: 1.2, category: "Fruits & Vegetables" },
  { id: 3, name: "Tomatoes", price: 0.9, category: "Fruits & Vegetables" },
  { id: 4, name: "Carrots", price: 0.8, category: "Fruits & Vegetables" },
  { id: 5, name: "Broccoli", price: 1.5, category: "Fruits & Vegetables" },
  { id: 6, name: "Orange Juice", price: 3.0, category: "Beverages" },
  { id: 7, name: "Cola Drink", price: 1.5, category: "Beverages" },
  { id: 8, name: "Iced Tea", price: 2.0, category: "Beverages" },
  { id: 9, name: "Milk", price: 2.5, category: "Dairy" },
  { id: 10, name: "Cheddar Cheese", price: 4.0, category: "Dairy" },
  { id: 11, name: "Yogurt", price: 1.8, category: "Dairy" },
  { id: 12, name: "Potato Chips", price: 1.3, category: "Snacks" },
  { id: 13, name: "Chocolate Bar", price: 1.1, category: "Snacks" },
  { id: 14, name: "Cookies", price: 2.2, category: "Snacks" },
  { id: 15, name: "Bread Loaf", price: 2.0, category: "Bakery" },
  { id: 16, name: "Croissants", price: 3.5, category: "Bakery" },
  { id: 17, name: "Bagels", price: 2.8, category: "Bakery" },
  { id: 18, name: "Chicken Breast", price: 5.0, category: "Meat" },
  { id: 19, name: "Ground Beef", price: 6.2, category: "Meat" },
  { id: 20, name: "Bacon", price: 4.5, category: "Meat" },
  { id: 21, name: "Frozen Pizza", price: 6.0, category: "Frozen" },
  { id: 22, name: "Frozen Vegetables", price: 2.5, category: "Frozen" },
  { id: 23, name: "Ice Cream", price: 3.8, category: "Frozen" },
  { id: 24, name: "Rice (1kg)", price: 2.0, category: "Pantry" },
  { id: 25, name: "Pasta", price: 1.7, category: "Pantry" },
  { id: 26, name: "Canned Tuna", price: 1.6, category: "Pantry" },
  { id: 27, name: "Peanut Butter", price: 3.4, category: "Pantry" },
  { id: 28, name: "Ketchup", price: 1.9, category: "Pantry" },
  { id: 29, name: "Sugar (1kg)", price: 1.3, category: "Pantry" },
  { id: 30, name: "Salt (500g)", price: 0.7, category: "Pantry" },
];

export const categories = ["All", ...Array.from(new Set(products.map((p) => p.category)))];
